version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_REACT_APP_API_URL=http://backend:5000/api/
    networks:
      - my-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      EMAIL_ADDRESS: "donna86@ethereal.email"
      EMAIL_USERNAME: "donna86@ethereal.email"
      EMAIL_PASSWORD: "5rBS8SsfWe9dWfv5eA"
      EMAIL_HOST: "smtp.ethereal.email"
      DB_CONNECTION_STRING: "Server=sql_server,1433;Initial Catalog=PhotographDb;User Id=sa;Password=YourPassword123!;Encrypt=False;"
      CORS: "http://frontend:5173"
    depends_on:
      - sql_server
    networks:
      - my-network

  sql_server:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
